let
    Source = Csv.Document(File.Contents("C:\Users\izuch\Downloads\archive\fifa21 raw data v2.csv"),[Delimiter=",", Columns=77, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Name", type text}, {"LongName", type text}, {"photoUrl", type text}, {"playerUrl", type text}, {"Nationality", type text}, {"Age", Int64.Type}, {"↓OVA", Int64.Type}, {"POT", Int64.Type}, {"Club", type text}, {"Contract", type text}, {"Positions", type text}, {"Height", type text}, {"Weight", type text}, {"Preferred Foot", type text}, {"BOV", Int64.Type}, {"Best Position", type text}, {"Joined", type date}, {"Loan Date End", type text}, {"Value", type text}, {"Wage", type text}, {"Release Clause", type text}, {"Attacking", Int64.Type}, {"Crossing", Int64.Type}, {"Finishing", Int64.Type}, {"Heading Accuracy", Int64.Type}, {"Short Passing", Int64.Type}, {"Volleys", Int64.Type}, {"Skill", Int64.Type}, {"Dribbling", Int64.Type}, {"Curve", Int64.Type}, {"FK Accuracy", Int64.Type}, {"Long Passing", Int64.Type}, {"Ball Control", Int64.Type}, {"Movement", Int64.Type}, {"Acceleration", Int64.Type}, {"Sprint Speed", Int64.Type}, {"Agility", Int64.Type}, {"Reactions", Int64.Type}, {"Balance", Int64.Type}, {"Power", Int64.Type}, {"Shot Power", Int64.Type}, {"Jumping", Int64.Type}, {"Stamina", Int64.Type}, {"Strength", Int64.Type}, {"Long Shots", Int64.Type}, {"Mentality", Int64.Type}, {"Aggression", Int64.Type}, {"Interceptions", Int64.Type}, {"Positioning", Int64.Type}, {"Vision", Int64.Type}, {"Penalties", Int64.Type}, {"Composure", Int64.Type}, {"Defending", Int64.Type}, {"Marking", Int64.Type}, {"Standing Tackle", Int64.Type}, {"Sliding Tackle", Int64.Type}, {"Goalkeeping", Int64.Type}, {"GK Diving", Int64.Type}, {"GK Handling", Int64.Type}, {"GK Kicking", Int64.Type}, {"GK Positioning", Int64.Type}, {"GK Reflexes", Int64.Type}, {"Total Stats", Int64.Type}, {"Base Stats", Int64.Type}, {"W/F", type text}, {"SM", type text}, {"A/W", type text}, {"D/W", type text}, {"IR", type text}, {"PAC", Int64.Type}, {"SHO", Int64.Type}, {"PAS", Int64.Type}, {"DRI", Int64.Type}, {"DEF", Int64.Type}, {"PHY", Int64.Type}, {"Hits", type text}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"Club", Text.Trim, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Trimmed Text","~","-",Replacer.ReplaceText,{"Contract"}),
    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Multiple", each if Text.EndsWith([Value], "M") then 1000000 else if Text.EndsWith([Value], "K") then 1000 else 1),
    #"Replaced Value1" = Table.ReplaceValue(#"Added Conditional Column","M","",Replacer.ReplaceText,{"Value"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","K","",Replacer.ReplaceText,{"Value"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","€","",Replacer.ReplaceText,{"Value"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value3",{{"Value", type number}, {"Multiple", type number}}),
    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type1", "Multiplication", each [Value] * [Multiple], type number),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Multiplication",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height", "Weight", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Multiplication", "Value", "Wage", "Release Clause", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Hits", "Multiple"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Value", "Multiple"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Multiplication", "Value"}}),
    #"Added Conditional Column6" = Table.AddColumn(#"Renamed Columns", "Custom", each if Text.EndsWith([Wage], "K") then 1000 else 1),
    #"Changed Type15" = Table.TransformColumnTypes(#"Added Conditional Column6",{{"Custom", type number}}),
    #"Replaced Value4" = Table.ReplaceValue(#"Changed Type15","K","",Replacer.ReplaceText,{"Wage"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","€","",Replacer.ReplaceText,{"Wage"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value5",{{"Wage", type number}}),
    #"Inserted Multiplication5" = Table.AddColumn(#"Changed Type2", "Multiplication", each [Wage] * [Custom], type number),
    #"Removed Columns6" = Table.RemoveColumns(#"Inserted Multiplication5",{"Wage", "Custom"}),
    #"Renamed Columns8" = Table.RenameColumns(#"Removed Columns6",{{"Multiplication", "Wage"}}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Renamed Columns8",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height", "Weight", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Value", "Wage", "Release Clause", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Hits"}),
    #"Added Conditional Column1" = Table.AddColumn(#"Reordered Columns5", "Multiple", each if Text.EndsWith([Release Clause], "M") then 1000000 else if Text.EndsWith([Release Clause], "K") then 1000 else 1),
    #"Replaced Value6" = Table.ReplaceValue(#"Added Conditional Column1","M","",Replacer.ReplaceText,{"Release Clause"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","K","",Replacer.ReplaceText,{"Release Clause"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","€","",Replacer.ReplaceText,{"Release Clause"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value8",{{"Release Clause", type number}}),
    #"Inserted Multiplication1" = Table.AddColumn(#"Changed Type3", "Multiplication", each [Release Clause] * [Multiple], type number),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Multiplication1",{"Release Clause", "Multiple"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height", "Weight", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Value", "Wage", "Multiplication", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Hits"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"Multiplication", "Release_Clause"}}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Value", Currency.Type}, {"Wage", Currency.Type}, {"Release_Clause", Currency.Type}}),
    #"Added Conditional Column2" = Table.AddColumn(#"Changed Type4", "Multiples", each if Text.EndsWith([Hits], "K") then 1000 else 1),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Conditional Column2",{{"Multiples", type number}}),
    #"Replaced Value9" = Table.ReplaceValue(#"Changed Type5","K","",Replacer.ReplaceText,{"Hits"}),
    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Value9",{{"Hits", type number}}),
    #"Inserted Multiplication2" = Table.AddColumn(#"Changed Type6", "Multiplication", each [Hits] * [Multiples], type number),
    #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Multiplication2",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height", "Weight", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Value", "Wage", "Release_Clause", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Multiplication", "Hits", "Multiples"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"Hits", "Multiples"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"Multiplication", "Hits"}}),
    #"Replaced Value10" = Table.ReplaceValue(#"Renamed Columns2","★","",Replacer.ReplaceText,{"W/F", "SM", "IR"}),
    #"Changed Type7" = Table.TransformColumnTypes(#"Replaced Value10",{{"W/F", Int64.Type}, {"SM", Int64.Type}, {"IR", Int64.Type}}),
    #"Added Conditional Column3" = Table.AddColumn(#"Changed Type7", "KG", each if Text.EndsWith([Weight], "lbs") then 0.453592 else 1),
    #"Replaced Value11" = Table.ReplaceValue(#"Added Conditional Column3","kg","",Replacer.ReplaceText,{"Weight"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","lbs","",Replacer.ReplaceText,{"Weight"}),
    #"Changed Type8" = Table.TransformColumnTypes(#"Replaced Value12",{{"KG", type number}, {"Weight", type number}}),
    #"Inserted Multiplication3" = Table.AddColumn(#"Changed Type8", "Multiplication", each [Weight] * [KG], type number),
    #"Removed Columns3" = Table.RemoveColumns(#"Inserted Multiplication3",{"Weight", "KG"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns3",{{"Multiplication", "Weight"}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns3",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height", "Weight", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Value", "Wage", "Release_Clause", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Hits"}),
    #"Renamed Columns4" = Table.RenameColumns(#"Reordered Columns3",{{"Weight", "Weight (KG)"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns4", "Height", Splitter.SplitTextByDelimiter("'", QuoteStyle.Csv), {"Height.1", "Height.2"}),
    #"Changed Type9" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Height.1", type text}, {"Height.2", type text}}),
    #"Added Conditional Column4" = Table.AddColumn(#"Changed Type9", "Custom", each if Text.EndsWith([Height.1], "cm") then 1 else 12),
    #"Changed Type10" = Table.TransformColumnTypes(#"Added Conditional Column4",{{"Custom", type number}}),
    #"Added Conditional Column5" = Table.AddColumn(#"Changed Type10", "Custom.1", each if Text.EndsWith([Height.1], "cm") then 1 else 0.393701),
    #"Replaced Value13" = Table.ReplaceValue(#"Added Conditional Column5","cm","",Replacer.ReplaceText,{"Height.1"}),
    #"Changed Type11" = Table.TransformColumnTypes(#"Replaced Value13",{{"Height.1", type number}}),
    #"Inserted Multiplication4" = Table.AddColumn(#"Changed Type11", "Multiplication", each [Custom] * [Height.1], type number),
    #"Changed Type12" = Table.TransformColumnTypes(#"Inserted Multiplication4",{{"Height.2", type number}}),
    #"Replaced Value14" = Table.ReplaceValue(#"Changed Type12",null,0,Replacer.ReplaceValue,{"Height.2"}),
    #"Inserted Addition" = Table.AddColumn(#"Replaced Value14", "Addition", each [Height.2] + [Multiplication], type number),
    #"Inserted Division" = Table.AddColumn(#"Inserted Addition", "Division", each [Addition] / [Custom.1], type number),
    #"Changed Type13" = Table.TransformColumnTypes(#"Inserted Division",{{"Division", Int64.Type}}),
    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type13",{{"Division", "Height"}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Renamed Columns5",{"Custom", "Custom.1", "Multiplication", "Addition"}),
    #"Renamed Columns6" = Table.RenameColumns(#"Removed Columns4",{{"Height", "Height (cm)"}}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Renamed Columns6",{"ID", "Name", "LongName", "photoUrl", "playerUrl", "Nationality", "Age", "↓OVA", "POT", "Club", "Contract", "Positions", "Height.1", "Height.2", "Height (cm)", "Weight (KG)", "Preferred Foot", "BOV", "Best Position", "Joined", "Loan Date End", "Value", "Wage", "Release_Clause", "Attacking", "Crossing", "Finishing", "Heading Accuracy", "Short Passing", "Volleys", "Skill", "Dribbling", "Curve", "FK Accuracy", "Long Passing", "Ball Control", "Movement", "Acceleration", "Sprint Speed", "Agility", "Reactions", "Balance", "Power", "Shot Power", "Jumping", "Stamina", "Strength", "Long Shots", "Mentality", "Aggression", "Interceptions", "Positioning", "Vision", "Penalties", "Composure", "Defending", "Marking", "Standing Tackle", "Sliding Tackle", "Goalkeeping", "GK Diving", "GK Handling", "GK Kicking", "GK Positioning", "GK Reflexes", "Total Stats", "Base Stats", "W/F", "SM", "A/W", "D/W", "IR", "PAC", "SHO", "PAS", "DRI", "DEF", "PHY", "Hits"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns4",{"Height.1", "Height.2", "photoUrl"}),
    #"Renamed Columns7" = Table.RenameColumns(#"Removed Columns5",{{"LongName", "Long_Name"}, {"playerUrl", "player_Url"}}),
    #"Changed Type14" = Table.TransformColumnTypes(#"Renamed Columns7",{{"Weight (KG)", Int64.Type}})
in
    #"Changed Type14"
